swagger: "2.0"
info:
  description: "This is a sample server Reddit clone on golang."
  version: "1.0.0"
  title: "Reddit clone"
  contact:
    email: "karpovdl@hotmail.com"
  license:
    name: "MIT License"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
- "http"
paths:
  /api/posts:
    get:
      tags:
      - "user"
      summary: "Get all posts"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "Post not found"
externalDocs:
  description: "Source"
  url: "http://github.com/karpovdl/rc"